models:
  - name: "Gemini 1.5 Pro"
    provider: "google"
    model: "gemini-1.5-pro-latest"
    apiKey: "AIzaSyDnLPT_O4jkadctfuJSfJhC0I7eqi3tN74"
  - name: "Gemini 1.5 Flash"
    provider: "google"
    model: "gemini-1.5-flash-latest"
    apiKey: "AIzaSyDnLPT_O4jkadctfuJSfJhC0I7eqi3tN74"

tabAutocompleteModel:
  name: "Gemini 1.5 Flash"
  provider: "google"
  model: "gemini-1.5-flash-latest"
  apiKey: "AIzaSyDnLPT_O4jkadctfuJSfJhC0I7eqi3tN74"

contextProviders:
  - name: "code"
  - name: "codebase"
  - name: "terminal"